# Setup
title:               PEMA
tagline:             'investigating metabarcoding'
description:         'A place for sharing news as well as thoughts and remarks on how to run metabarcoding analyses using the PEMA containers or other software. Made by <a href="hariszaf.github.io/" target="_blank">Haris Zafeiropoulos</a>.'
url:                 https://hariszaf.github.io/metabarcoding_toolkit/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Haris Zafeiropoulos
  url:               hariszaf.github.io/
  email:             haris-zaf@hcmr.gr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
